### ISSUE TITLE
500 error without clear cause when php_exif module is not installed

### ISSUE THREAD

**Issue by tmsvl** [samayo/bulletproof#102]
Hi,

In bulletproof.php:300 the errors from this line are ignored with the @ character:
$this->mime = @$this->acceptedMimes[exif_imagetype($tmp_name)];

When php_exif is not installed, this causes the server to return a 500 error without any indication of the root cause.

**Comment by samayo** [comment]
Sorry. Email was down for 2 weeks and didn't get any notifications. 

Anyway, the error is there for a reason. You need the php_exif library to be able to upload with bulletproof. Otherwise it won't work. the exif library is used to authenticate the image uploaded for security reasons, so it is important

cheers
