### ISSUE TITLE
How do I upload a large image and resize it to a small size (thumb) and save it in another folder?

### ISSUE THREAD

**Issue by jodyshop** [samayo/bulletproof#143]
What I want is to upload a large image and keep it inside the uploads folder, for example:
site.com/uploads/2024/05/large_image.jpg

Then, it resizes the same image using the Bulletproof\Utils\resize function and moves it to another folder as follows:
site.com/uploads/thumbs/2024/05/thumb_image.jpg

Is that approach possible with Bulletproof Library?
I appreciate any help you can provide.

**Comment by samayo** [comment]
yes what you describe is possible. simply first upload the image and resize it. try the code shown in https://github.com/samayo/bulletproof/tree/master/src/utils 

```
if($image["picture"]){
$upload = $image->upload();

if($upload){
// 
}
```
in the above example $upload should contain the data of the uploaded image, you can use getPath() as $upload->getPath(); to get the full path of the image from here

from there, you can use the resize library to feed it all the params it requires. 

```
Bulletproof\Utils\resize(
  $image->getPath(), 
  $image->getMime(),
  $image->getWidth(),
  $image->getHeight(),
  50,
  50
);
```

it should work, if you want to make one or more copies of your images, i suggest you use `copy` https://www.php.net/copy 

once you upload the image make sure if reize is making a copy or resizing the original image (i forgot how to works, it's been many year since i made the resize tool)

if the original image is being used, then use copy
