### ISSUE TITLE
Option to strip non-essential EXIF data

### ISSUE THREAD

**Issue by scottconnerly** [samayo/bulletproof#42]
https://security.stackexchange.com/questions/235/what-steps-should-be-taken-to-validate-user-uploaded-images-within-an-applicatio/3016#3016

Because of GIFAR, XSS, and File Inclusion
Additionally, not as a technical security concern, but as a meatspace security concern, it'd be nice for it to be stripping exif things like geocodes.

**Comment by Danack** [comment]
The stuff discussed in that link is irrelevant to a proper security solution. In the same as suggesting that stripslashes be used on user input to prevent SQL escaping, when the correct solution is to use prepared statements or whitelisting of user input.

In that link they are talking about things like the user embedding `<?php maliciousCode(); ?>` in an exif tag, and then getting PHP to execute that image. The correct solution to that problem is to:

* place uploaded images in a separate place from where code in stored, so that it is hard for it to be 'included' by the attacker.
* set the permissions of the uploaded file to not be executable.

As soon as a user is able to upload a file to a server and is able to execute it, that server should be considered compromised. Trying to block just this single attack route by stripping 'bad text' is just trying to solve the problem at the wrong level.

> it'd be nice

IMNSHO you need to provide actual reasons for adding functionality in a library not just a vague "oo, why don't we" as everything added to a library adds a burden for maintaining it.
