### ISSUE TITLE
return NULL on getMime

### ISSUE THREAD

**Issue by pararang** [samayo/bulletproof#61]
Hi, Me again,

currently not use it on my project but I think I need to tell you that there is NULL returned when calling to getMime. Thanks

**Comment by samayo** [comment]
Hi, it's me again :) 

You must have called `getMime();` before calling `upload();` to get that response. Initially, I wanted the mime to appear after upload was called, since the mime verification was being done inside `upload()` function. 

Scrutinizer-CI will complain now that I have called PHP's `getImageMime()` method in those both functions, but I see it is important to be able to check the mime before uploading. 

So, try it again. I have released 2.0.5 and let me know if there are other issues

**Comment by pararang** [comment]
@samayo Wooo... fast response. I have tried it and it works.

In addition, getMime will help when the executions flow needed to store file name (with extension) to the database before call `upload()`. In case failed when `upload()`, you can roll back the DB. I think it needs less effort than deleting the file if failed to write to DB. (need more research :) )
