### ISSUE TITLE
Failure to upload pdf files

### ISSUE THREAD

**Issue by EpicEdwardo** [samayo/bulletproof#67]
Hey! 

I'm fairly certain it is possible to upload pdf files with bulletproof. But I can't seem to at all. In fact, I can't seem to upload any files other than .jpg files. I've used the setMime attribute to set it specifically to pdfs but no avail. And I'm using the correct code and all (or of course it wouldn't allow me to upload jpgs.

    require_once  "path/to/bulletproof.php";

    $image = new Bulletproof\Image($_FILES);

    if($image["pictures"]){
    $upload = $image->upload(); 
	
    if($upload){
        echo $upload->getFullPath(); // uploads/cat.gif
    }else{
        echo $image["error"]; 
    }
    }

What could the problem be you think? It befuddles me all this.

**Comment by samayo** [comment]
Hi. 

It's not possible to upload a .pdf file type, even if you pass it to the setMime() function. That method will only allow you to choose which image type to upload, not file type. This is because, bulletproof id internally instructed to upload only image types that are given to setMime() function. 


About not being able to upload other than jpg/jpeg ... check you are using the latest version of bulletproof and maybe pass the mimetypes as: 
```php
$image = new Bulletproof\Image($_FILES);
$image->setMime(['gif', 'jpeg', 'png']);
```

remember bulletproof will not upload a file or a corrupted image even if it ends with jpg/png/gif... 

check those and let me know

**Comment by samayo** [comment]
closing this as fixed
