### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [samayo/bulletproof#89]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by samayo** [comment]
haha, thanks. go for it, i love the idea 💯

**Comment by mansya** [comment]
I have desing logo for this project. do you like it ? what do you think ?

![autocomplete](https://user-images.githubusercontent.com/33461607/43463762-9d1e9806-9503-11e8-96d7-bca2ee970a50.png)

sorry for a long time respon. I'm just busy for a moment.

**Comment by samayo** [comment]
Hey, thanks. I like it. It looks cool.

Just a small suggestion. I don't think the text "Bullet Proof" is needed. Also the hexagon shape doesn't really seem it belongs there. I would prefer if the color was only black and white. Maybe the bullet hitting  something at 45 degree and the head of the bullet would be fractured. 

Of course this is unreasonable demand since you are just trying help, but take as much time as you need and if you want then you can improve it a bit. But this is a good start.

**Comment by mansya** [comment]
what do you think if like this ?

![bulletproof bw](https://user-images.githubusercontent.com/33461607/43471492-51e2440c-9515-11e8-9a18-4ba79e0917d5.png)

for the bullet would be fractured. I'm sorry for that request

**Comment by samayo** [comment]
Its okay. This one looks better but not exactly what I had in mind. I will think about it and let you know. 

Again, thanks.

**Comment by mansya** [comment]
can I make pull requests?

**Comment by samayo** [comment]
Yes, but not on this one. I will let you know if I find an example or draw something. This is a good logo, but not the type I was hoping for
