### ISSUE TITLE
Blank page after form is submitted with no error message

### ISSUE THREAD

**Issue by helloromero** [samayo/bulletproof#98]
Blank page after form post with no error message

Any idea what's wrong?

**Comment by twistedpixel** [comment]
Turn on PHP error reporting for a start.

**Comment by salimsaaty** [comment]
I noticed it through my access log that it's throwing a 500 error code actually, while not throwing it on the webpage even with error reporting, there must be something wrong with my PHP conf.
I started deleting lines that I thought were the culprit and I think it's the resizing and cropping that's giving me trouble although it's working fine locally, I had permission problems at first but I solved that since without resizing and cropping it's working as it should

**Comment by twistedpixel** [comment]
In future, if you cannot get PHP errors to display, try pasting this in the constructor of your highest level controller: `ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);`

Sometimes trying to turn on error reporting in your config file or whatever can result in them being overridden and disabled again if you're, for example, using a framework.

Also, some hosts don't seem to allow error reporting to be enabled within PHP and you need to go into the hosting control panel to enable it. I've seen this behavior in Plesk for example.

**Comment by salimsaaty** [comment]
Aaaand solved, apparently I needed php-gd installed on the system, locally it was working because it was probably bundled up.
I hope if the symptoms were the same to the OP, if not then you can link other people having this error here
